# Generated by Django 6.0.5 on 2026-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
